import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/nav/Navbar'
import SectionCard from '../components/card/SectionCard'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mt2.svg" />
      </Head>
      <Navbar userName="rohit@gmail.com" />
      <div>
        <SectionCard title="Disney"/>
        
      
      </div>
     
      

     
    </div>
  )
}
